name: CI Pipeline

on:
  push:
    branches:
      - master # This triggers the workflow on push to the main branch
  pull_request:
    branches:
      - master # This triggers the workflow on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Step 3: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 4: Build Docker image
    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/converter2:latest .

    # Step 5: Run tests (optional, add your own test command)
    - name: Run tests
      run: |
        docker run --rm ${{ secrets.DOCKER_USERNAME }}/converter2:latest pytest

    # Step 6: Push Docker image to Docker Hub
    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/converter2:latest
